apiVersion: v1
kind: Pod
metadata:
  name: sidecar
spec:
  imagePullSecrets:
    - name:  regcred
  volumes:
  - name: shared-logs 
    emptyDir: {}
  containers:
  - name: main-container
    image: busybox 
    command: ["/bin/sh"]
    args: ["-c", "while true; do ping google.com  >> /tmp/index-input.html; sleep 90;done"]
    volumeMounts:
    - name: shared-logs
      mountPath: /var/logs
  - name: sidecar-container
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do cat /tmp/index-input.html  >> /tmp/index-input.html; sleep 90;done"]
    ports:
      - containerPort: 80
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log
